name: Build-PhoneControl-APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build
        run: |
          npm install --legacy-peer-deps
          npm install @capacitor/cli @capacitor/android
          rm -rf android
          npx cap add android
          npm run build --if-present
          npx cap sync android
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: My-Phone-Control-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
